[package]
name = "solana-presigner"
description = "A Solana `Signer` implementation representing an externally-constructed `Signature`."
documentation = "https://docs.rs/solana-presigner"
version = "3.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
solana-pubkey = { workspace = true }
solana-signature = { workspace = true, features = ["verify"] }
solana-signer = { workspace = true }
