[package]
name = "solana-sdk"
description = "Solana SDK"
documentation = "https://docs.rs/solana-sdk"
readme = "README.md"
version = "2.3.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
include = ["src/**/*", "README.md"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[lib]
crate-type = ["rlib"]

[features]
default = [
    "borsh",
    "full",  # functionality that is not compatible or needed for on-chain programs
]
full = [
    "solana-signature",
    "solana-pubkey/rand",
    "dep:solana-offchain-message",
    "dep:solana-presigner",
    "dep:solana-shred-version",
    "dep:solana-signer",
    "dep:solana-transaction-error",
]
borsh = ["solana-program/borsh"]
dev-context-only-utils = [
    "solana-program/dev-context-only-utils",
]
frozen-abi = [
    "solana-program/frozen-abi",
    "solana-short-vec/frozen-abi",
    "solana-signature/frozen-abi",
    "solana-transaction-error/frozen-abi",
]

[dependencies]
bincode = { workspace = true }
bs58 = { workspace = true }
ed25519-dalek = { workspace = true, features = ["rand_core"] }
ed25519-dalek-bip32 = { workspace = true }
derivation-path = { workspace = true }
qstring = { workspace = true }
uriparse = { workspace = true }
five8 = { workspace = true }
hmac = { workspace = true }
pbkdf2 = { workspace = true }
rand = { workspace = true }
sha2 = { workspace = true }
serde_bytes = { workspace = true }
siphasher = { workspace = true }
solana-account-info = { workspace = true }
solana-clock = { workspace = true }
solana-frozen-abi = { workspace = true, optional = true }
solana-frozen-abi-macro = { workspace = true, optional = true }
solana-instruction-error = { workspace = true }
solana-logger = { workspace = true, optional = true }
solana-sysvar = { workspace = true, features = ["bincode"] }
serde = { workspace = true }
serde_derive = { workspace = true }
solana-epoch-info = { workspace = true, features = ["serde"] }
solana-hash = { workspace = true }
solana-instruction = { workspace = true, features = ["serde"] }
solana-message = { workspace = true, features = ["bincode", "blake3", "serde"] }
solana-offchain-message = { workspace = true, optional = true, features = ["verify"] }
solana-presigner = { workspace = true, optional = true }
solana-program = { workspace = true }
solana-program-memory = { workspace = true }
solana-pubkey = { workspace = true, default-features = false, features = [
    "std",
] }
solana-sanitize = { workspace = true }
solana-sdk-ids = { workspace = true }
solana-sdk-macro = { workspace = true }
solana-serde = { workspace = true }
solana-serde-varint = { workspace = true }
solana-short-vec = { workspace = true }
solana-shred-version = { workspace = true, optional = true }
solana-signature = { workspace = true, features = [
    "rand",
    "serde",
    "std",
    "verify",
], optional = true }
solana-signer = { workspace = true, optional = true }
solana-time-utils = { workspace = true }
solana-transaction-error = { workspace = true, features = [
    "serde",
], optional = true }
thiserror = { workspace = true }

[dev-dependencies]
solana-instructions-sysvar = { workspace = true, features = ["dev-context-only-utils"] }
solana-program = { workspace = true, features = ["dev-context-only-utils"] }
solana-sdk = { path = ".", features = ["dev-context-only-utils"] }

[lints]
workspace = true
